// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/entity/chain_entity/interface.go

// Package mock_chainentity is a generated GoMock package.
package mock_chainentity

import (
	reflect "reflect"

	request "github.com/consolelabs/indexer-api/pkg/request"
	response "github.com/consolelabs/indexer-api/pkg/response"
	gomock "github.com/golang/mock/gomock"
)

// MockIChainEntity is a mock of IChainEntity interface.
type MockIChainEntity struct {
	ctrl     *gomock.Controller
	recorder *MockIChainEntityMockRecorder
}

// MockIChainEntityMockRecorder is the mock recorder for MockIChainEntity.
type MockIChainEntityMockRecorder struct {
	mock *MockIChainEntity
}

// NewMockIChainEntity creates a new mock instance.
func NewMockIChainEntity(ctrl *gomock.Controller) *MockIChainEntity {
	mock := &MockIChainEntity{ctrl: ctrl}
	mock.recorder = &MockIChainEntityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIChainEntity) EXPECT() *MockIChainEntityMockRecorder {
	return m.recorder
}

// GetChains mocks base method.
func (m *MockIChainEntity) GetChains(query request.GetChainsQuery) (*response.GetChainsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChains", query)
	ret0, _ := ret[0].(*response.GetChainsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChains indicates an expected call of GetChains.
func (mr *MockIChainEntityMockRecorder) GetChains(query interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChains", reflect.TypeOf((*MockIChainEntity)(nil).GetChains), query)
}
