// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/entity/contract/interface.go

// Package mock_contract is a generated GoMock package.
package mock_contract

import (
	reflect "reflect"

	model "github.com/consolelabs/indexer-api/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIContractEntity is a mock of IContractEntity interface.
type MockIContractEntity struct {
	ctrl     *gomock.Controller
	recorder *MockIContractEntityMockRecorder
}

// MockIContractEntityMockRecorder is the mock recorder for MockIContractEntity.
type MockIContractEntityMockRecorder struct {
	mock *MockIContractEntity
}

// NewMockIContractEntity creates a new mock instance.
func NewMockIContractEntity(ctrl *gomock.Controller) *MockIContractEntity {
	mock := &MockIContractEntity{ctrl: ctrl}
	mock.recorder = &MockIContractEntityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContractEntity) EXPECT() *MockIContractEntityMockRecorder {
	return m.recorder
}

// AddContract mocks base method.
func (m *MockIContractEntity) AddContract(contract model.Contract, name, symbol string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContract", contract, name, symbol)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddContract indicates an expected call of AddContract.
func (mr *MockIContractEntityMockRecorder) AddContract(contract, name, symbol interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContract", reflect.TypeOf((*MockIContractEntity)(nil).AddContract), contract, name, symbol)
}

// GetContract mocks base method.
func (m *MockIContractEntity) GetContract(address string) (*model.Contract, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContract", address)
	ret0, _ := ret[0].(*model.Contract)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContract indicates an expected call of GetContract.
func (mr *MockIContractEntityMockRecorder) GetContract(address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContract", reflect.TypeOf((*MockIContractEntity)(nil).GetContract), address)
}
