// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/service/chain_explorer/interface.go

// Package mock_chain_explorer is a generated GoMock package.
package mock_chain_explorer

import (
	reflect "reflect"

	model "github.com/consolelabs/indexer-api/pkg/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIService is a mock of IService interface.
type MockIService struct {
	ctrl     *gomock.Controller
	recorder *MockIServiceMockRecorder
}

// MockIServiceMockRecorder is the mock recorder for MockIService.
type MockIServiceMockRecorder struct {
	mock *MockIService
}

// NewMockIService creates a new mock instance.
func NewMockIService(ctrl *gomock.Controller) *MockIService {
	mock := &MockIService{ctrl: ctrl}
	mock.recorder = &MockIServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIService) EXPECT() *MockIServiceMockRecorder {
	return m.recorder
}

// GetCreationBlockNumber mocks base method.
func (m *MockIService) GetCreationBlockNumber(arg0 model.Contract) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCreationBlockNumber", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCreationBlockNumber indicates an expected call of GetCreationBlockNumber.
func (mr *MockIServiceMockRecorder) GetCreationBlockNumber(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCreationBlockNumber", reflect.TypeOf((*MockIService)(nil).GetCreationBlockNumber), arg0)
}
