// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contract/erc721": {
            "post": {
                "description": "Add contract",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Add contract",
                "parameters": [
                    {
                        "description": "Add contract request",
                        "name": "Request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AddContractRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ResponseString"
                        }
                    }
                }
            }
        },
        "/contract/{address}": {
            "get": {
                "description": "Get contract",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Contract"
                ],
                "summary": "Get contract",
                "parameters": [
                    {
                        "type": "string",
                        "description": "contract address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ContractResponse"
                        }
                    }
                }
            }
        },
        "/nft": {
            "get": {
                "description": "Get nft collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "address",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "paintswap",
                            "nftkey",
                            "opensea",
                            "looksrare"
                        ],
                        "type": "string",
                        "description": "marketplace",
                        "name": "marketplace",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "search collection name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "one_day_volume",
                            "-one_day_volume",
                            "seven_day_volume",
                            "-seven_day_volume",
                            "thirty_day_volume",
                            "-thirty_day_volume",
                            "all_time_volume",
                            "-all_time_volume",
                            "floor_price",
                            "-floor_price",
                            "supply",
                            "-supply",
                            "name",
                            "-name",
                            "owners",
                            "-owners"
                        ],
                        "type": "string",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftCollectionsResponse"
                        }
                    }
                }
            }
        },
        "/nft/metadata/attributes-icon": {
            "get": {
                "description": "Get nft trait icons",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft trait icons",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "name": "trait_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NftMetadataAttributesIconResponse"
                        }
                    }
                }
            }
        },
        "/nft/ticker": {
            "get": {
                "description": "Get nft daily trading volume",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft daily trading volume",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NftTradingVolumeResponse"
                        }
                    }
                }
            }
        },
        "/nft/ticker/{collection_address}": {
            "get": {
                "description": "Get floor prices snapshot by nft address (top 7d / 1m / ...)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get floor prices snapshot by nft address (top 7d / 1m / ...)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "From date in UNIX millisecond (eg. 1392577232000)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "To date in UNIX millisecond (eg. 1422577232000)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NftCollectionTickersResponse"
                        }
                    }
                }
            }
        },
        "/nft/ticker/{collection_address}/{token_id}": {
            "get": {
                "description": "Get nft token ticker",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft token ticker",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "token_id",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "From date in UNIX millisecond (eg. 1392577232000)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "To date in UNIX millisecond (eg. 1422577232000)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NftTokenTickersDataResponse"
                        }
                    }
                }
            }
        },
        "/nft/{collection_address}": {
            "get": {
                "description": "Get tokens of a nft collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get tokens of a nft collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "paintswap",
                                "nftkey",
                                "opensea",
                                "looksrare"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "marketplaces",
                        "name": "marketplaces",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "example": "mask=Television Head,Zorro Mask",
                        "description": "token traits/attributes",
                        "name": "traits",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "collectionFormat": "multi",
                        "example": 11,
                        "description": "traits count",
                        "name": "traits_count",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "eth",
                            "ftm"
                        ],
                        "type": "string",
                        "description": "payment token/currency",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "listed",
                            "sold",
                            "cancelled"
                        ],
                        "type": "string",
                        "description": "listing status",
                        "name": "listing_status",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "buy_now",
                            "auction"
                        ],
                        "type": "string",
                        "description": "listing type",
                        "name": "listing_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "example": 10,
                        "description": "listing price max",
                        "name": "price_max",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "example": 0,
                        "description": "listing price min",
                        "name": "price_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "rarity rank max",
                        "name": "rarity_rank_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "rarity rank min",
                        "name": "rarity_rank_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "name",
                            "-name",
                            "token_id",
                            "-token_id",
                            "amount",
                            "-amount",
                            "rarity_rank",
                            "-rarity_rank",
                            "rarity_score",
                            "-rarity_score",
                            "rarity_tier",
                            "-rarity_tier"
                        ],
                        "type": "string",
                        "description": "sort by",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "token ID",
                        "name": "token_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftTokensResponse"
                        }
                    }
                }
            }
        },
        "/nft/{collection_address}/metadata": {
            "get": {
                "description": "Get nft collection metadata",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft collection metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftCollectionMetadataResponse"
                        }
                    }
                }
            }
        },
        "/nft/{collection_address}/{token_id}": {
            "get": {
                "description": "Get nft details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft by address",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token Id",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.NftTokenResponse"
                        }
                    }
                }
            }
        },
        "/nft/{collection_address}/{token_id}/activity": {
            "get": {
                "description": "Get nft token activities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft token activities",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token Id",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "marketplace name",
                        "name": "marketplace",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftTokenActivitiesResponse"
                        }
                    }
                }
            }
        },
        "/nft/{collection_address}/{token_id}/transaction-history": {
            "get": {
                "description": "Get nft token tx history",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "NFT"
                ],
                "summary": "Get nft token tx history",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "token Id",
                        "name": "token_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collection address",
                        "name": "collection_address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftTokenTransactionHistory"
                        }
                    }
                }
            }
        },
        "/{wallet_address}/nft": {
            "get": {
                "description": "Get nft tokens by owner address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "Get nft tokens by owner address",
                "parameters": [
                    {
                        "type": "string",
                        "description": "wallet address",
                        "name": "wallet_address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "chain ID",
                        "name": "chain_id",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "name": "collection_addresses",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page index",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "size",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "collection_address",
                            "token_id",
                            "name",
                            "amount",
                            "rarity_rank",
                            "rarity_score",
                            "rarity_tier",
                            "-collection_address",
                            "-token_id",
                            "-name",
                            "-amount",
                            "-rarity_rank",
                            "-rarity_score",
                            "-rarity_tier"
                        ],
                        "type": "string",
                        "description": "sort by",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.GetNftTokensResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Chain": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "is_evm": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "scan_url": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "model.MarketplacePlatform": {
            "type": "object",
            "properties": {
                "icon_url": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.NftCollection": {
            "type": "object",
            "properties": {
                "chain": {
                    "$ref": "#/definitions/model.Chain"
                },
                "chain_id": {
                    "type": "integer"
                },
                "collection_address": {
                    "type": "string"
                },
                "contract_scan": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "discord": {
                    "type": "string"
                },
                "erc_format": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "is_notify_synced": {
                    "type": "boolean"
                },
                "is_rarity_calculated": {
                    "type": "boolean"
                },
                "last_updated_time": {
                    "type": "string"
                },
                "marketplace": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftListingMarketplace"
                    }
                },
                "marketplace_collections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftMarketplaceCollection"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owners": {
                    "type": "integer"
                },
                "stats": {
                    "$ref": "#/definitions/model.ViewNftCollectionStats"
                },
                "supply": {
                    "type": "integer"
                },
                "symbol": {
                    "type": "string"
                },
                "twitter": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "model.NftListing": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "contract_address": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "from_address": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "last_updated_time": {
                    "type": "string"
                },
                "listing_price": {
                    "type": "string"
                },
                "listing_price_obj": {
                    "$ref": "#/definitions/model.Price"
                },
                "listing_status": {
                    "type": "string"
                },
                "listing_type": {
                    "type": "string"
                },
                "marketplace": {
                    "$ref": "#/definitions/model.MarketplacePlatform"
                },
                "payment_token": {
                    "type": "integer"
                },
                "platform_id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "string"
                },
                "sold_price": {
                    "type": "string"
                },
                "sold_price_obj": {
                    "$ref": "#/definitions/model.Price"
                },
                "to_address": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                }
            }
        },
        "model.NftListingMarketplace": {
            "type": "object",
            "properties": {
                "contract_address": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "floor_price": {
                    "type": "string"
                },
                "listing_price": {
                    "type": "string"
                },
                "listing_status": {
                    "type": "string"
                },
                "payment_token": {
                    "type": "string"
                },
                "payment_token_decimals": {
                    "type": "string"
                },
                "platform_id": {
                    "type": "integer"
                },
                "platform_name": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                }
            }
        },
        "model.NftMarketplaceCollection": {
            "type": "object",
            "properties": {
                "collection_address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "floor_price": {
                    "type": "number"
                },
                "floor_price_obj": {
                    "$ref": "#/definitions/model.Price"
                },
                "platform": {
                    "$ref": "#/definitions/model.MarketplacePlatform"
                },
                "platform_id": {
                    "type": "integer"
                },
                "royalty_address": {
                    "type": "string"
                },
                "royalty_percentage": {
                    "type": "number"
                },
                "token_id": {
                    "type": "integer"
                },
                "total_volume": {
                    "type": "number"
                },
                "total_volume_obj": {
                    "$ref": "#/definitions/model.Price"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "model.NftMetadataAttributesIcon": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "discord_icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "trait_type": {
                    "type": "string"
                },
                "unicode_icon": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "model.NftOwner": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "collection_address": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "last_updated_time": {
                    "type": "string"
                },
                "owner_address": {
                    "type": "string"
                },
                "token": {
                    "description": "specify references to join/preload nft_token\n\u003c-:false    Disable write permission",
                    "$ref": "#/definitions/model.NftToken"
                },
                "token_id": {
                    "type": "string"
                }
            }
        },
        "model.NftToken": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "attributes": {
                    "description": "disable write",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftTokenAttribute"
                    }
                },
                "collection_address": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "image_cdn": {
                    "type": "string"
                },
                "image_content_type": {
                    "type": "string"
                },
                "is_self_hosted": {
                    "type": "boolean"
                },
                "last_updated_time": {
                    "type": "string"
                },
                "listing": {
                    "description": "Listing    *NftListing         ` + "`" + `json:\"listing\" gorm:\"foreignKey:TokenId,ContractAddress;references:TokenId,CollectionAddress;\u003c-:false\"` + "`" + ` // disable write",
                    "$ref": "#/definitions/model.NftListing"
                },
                "listing_marketplace": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftListingMarketplace"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/model.NftOwner"
                },
                "rarity": {
                    "description": "Attributes []NftTokenAttribute ` + "`" + `json:\"attributes\" gorm:\"foreignkey:TokenId,CollectionAddress;references:TokenId,CollectionAddress;\u003c-:false\"` + "`" + ` // disable write",
                    "$ref": "#/definitions/model.NftTokenRarity"
                },
                "rarity_rank": {
                    "type": "integer"
                },
                "rarity_score": {
                    "type": "string"
                },
                "rarity_tier": {
                    "type": "string"
                },
                "thumbnail_cdn": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                }
            }
        },
        "model.NftTokenAttribute": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "collection_address": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "frequency": {
                    "type": "string"
                },
                "rarity": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "trait_type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "model.NftTokenRarity": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "integer"
                },
                "rarity": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.NftTxHistory": {
            "type": "object",
            "properties": {
                "contract_address": {
                    "type": "string"
                },
                "created_time": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "listing_status": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "transaction_hash": {
                    "type": "string"
                }
            }
        },
        "model.Price": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "amount_in_usd": {
                    "description": "TODO: get exchange rate and calculate",
                    "type": "number"
                },
                "token": {
                    "$ref": "#/definitions/model.Token"
                }
            }
        },
        "model.Token": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "decimals": {
                    "type": "integer"
                },
                "icon_url": {
                    "type": "string"
                },
                "is_native": {
                    "type": "boolean"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "model.ViewNftCollectionStats": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "all_time_volume": {
                    "$ref": "#/definitions/model.Price"
                },
                "all_time_volume_change": {
                    "type": "number"
                },
                "all_time_volume_change_str": {
                    "type": "string"
                },
                "floor_price": {
                    "$ref": "#/definitions/model.Price"
                },
                "one_day_volume": {
                    "$ref": "#/definitions/model.Price"
                },
                "one_day_volume_change": {
                    "type": "number"
                },
                "one_day_volume_change_str": {
                    "type": "string"
                },
                "seven_day_volume": {
                    "$ref": "#/definitions/model.Price"
                },
                "seven_day_volume_change": {
                    "type": "number"
                },
                "seven_day_volume_change_str": {
                    "type": "string"
                },
                "thirty_day_volume": {
                    "$ref": "#/definitions/model.Price"
                },
                "thirty_day_volume_change": {
                    "type": "number"
                },
                "thirty_day_volume_change_str": {
                    "type": "string"
                }
            }
        },
        "request.AddContractRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "response.ContractResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.ContractResponseData"
                }
            }
        },
        "response.ContractResponseData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer"
                },
                "created_time": {
                    "type": "string"
                },
                "creation_block": {
                    "type": "integer"
                },
                "grpcAddress": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_proxy": {
                    "type": "boolean"
                },
                "is_synced": {
                    "type": "boolean"
                },
                "last_updated_block": {
                    "type": "integer"
                },
                "last_updated_time": {
                    "type": "string"
                },
                "logic_address": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "response.GetNftCollectionMetadataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/model.NftCollection"
                }
            }
        },
        "response.GetNftCollectionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftCollection"
                    }
                },
                "page": {
                    "description": "page index",
                    "type": "integer"
                },
                "size": {
                    "description": "page size",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetNftTokenActivitiesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftListing"
                    }
                },
                "page": {
                    "description": "page index",
                    "type": "integer"
                },
                "size": {
                    "description": "page size",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.GetNftTokenTransactionHistory": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftTxHistory"
                    }
                }
            }
        },
        "response.GetNftTokensResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftToken"
                    }
                },
                "page": {
                    "description": "page index",
                    "type": "integer"
                },
                "size": {
                    "description": "page size",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.NftCollectionTickersData": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "chain": {
                    "$ref": "#/definitions/model.Chain"
                },
                "collection_image": {
                    "type": "string"
                },
                "floor_price": {
                    "$ref": "#/definitions/model.Price"
                },
                "items": {
                    "type": "integer"
                },
                "last_sale_price": {
                    "$ref": "#/definitions/model.Price"
                },
                "marketplaces": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owners": {
                    "type": "integer"
                },
                "price_change_1d": {
                    "type": "string"
                },
                "price_change_30d": {
                    "type": "string"
                },
                "price_change_7d": {
                    "type": "string"
                },
                "tickers": {
                    "$ref": "#/definitions/response.TokenTickers"
                },
                "total_volume": {
                    "$ref": "#/definitions/model.Price"
                }
            }
        },
        "response.NftCollectionTickersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.NftCollectionTickersData"
                }
            }
        },
        "response.NftMetadataAttributesIconResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftMetadataAttributesIcon"
                    }
                },
                "page": {
                    "description": "page index",
                    "type": "integer"
                },
                "size": {
                    "description": "page size",
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.NftTokenAttributeResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "frequency": {
                    "type": "string"
                },
                "rarity": {
                    "type": "string"
                },
                "trait_type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "response.NftTokenData": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/response.NftTokenAttributeResponse"
                    }
                },
                "collection_address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "image_cdn": {
                    "type": "string"
                },
                "image_content_type": {
                    "type": "string"
                },
                "marketplace": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.NftListingMarketplace"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/model.NftOwner"
                },
                "rarity": {
                    "$ref": "#/definitions/response.NftTokenRarityResponse"
                },
                "thumbnail_cdn": {
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                }
            }
        },
        "response.NftTokenRarityResponse": {
            "type": "object",
            "properties": {
                "rank": {
                    "type": "integer"
                },
                "rarity": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "response.NftTokenResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.NftTokenData"
                }
            }
        },
        "response.NftTokenTickersData": {
            "type": "object",
            "properties": {
                "collection_address": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "floor_price": {
                    "$ref": "#/definitions/model.Price"
                },
                "image": {
                    "type": "string"
                },
                "image_cdn": {
                    "type": "string"
                },
                "last_sale_price": {
                    "$ref": "#/definitions/model.Price"
                },
                "name": {
                    "type": "string"
                },
                "price_change_1d": {
                    "type": "string"
                },
                "price_change_30d": {
                    "type": "string"
                },
                "price_change_7d": {
                    "type": "string"
                },
                "rarity_rank": {
                    "type": "integer"
                },
                "rarity_score": {
                    "type": "string"
                },
                "rarity_tier": {
                    "type": "string"
                },
                "tickers": {
                    "$ref": "#/definitions/response.TokenTickers"
                },
                "token_id": {
                    "type": "string"
                }
            }
        },
        "response.NftTokenTickersDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.NftTokenTickersData"
                }
            }
        },
        "response.NftTradingVolume": {
            "type": "object",
            "properties": {
                "collection_address": {
                    "type": "string"
                },
                "collection_chain_id": {
                    "type": "integer"
                },
                "collection_name": {
                    "type": "string"
                },
                "collection_symbol": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "trading_volume": {
                    "type": "number"
                }
            }
        },
        "response.NftTradingVolumeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.NftTradingVolume"
                }
            }
        },
        "response.ResponseString": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                }
            }
        },
        "response.TokenTickers": {
            "type": "object",
            "properties": {
                "prices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Price"
                    }
                },
                "timestamps": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server celler server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
