name: Run CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup dependencies
        run: |
          make setup
          go install -v ./...

      - name: Setup database
        run: |
          make init_test
          make migrate-test
      
      - name: Test
        run: go test --cover ./...